title: Yksityisyys
description: Yksityisyys on ihmisoikeus.
theme: just-the-docs
language: fi

url: https://yksityisyys.fi
baseurl: ""

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
